name: "Dependabot Automerge - Action"

# Credits: https://stackoverflow.com/a/64515475/7341726

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Automerge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
